package com.flash.memcached;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'c4dev' at '2/26/17 12:44 AM' with Gradle 2.11
 *
 * @author c4dev, @date 2/26/17 12:44 AM
 */
public class MainTest {
    @Test public void testSomeLibraryMethod() {
        Main classUnderTest = new Main();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
