package com.flash.memcached;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'c4dev' at '2/26/17 12:44 AM' with Gradle 2.11
 *
 * @author c4dev, @date 2/26/17 12:44 AM
 */
public class Main {
    public boolean someLibraryMethod() {
        return true;
    }
}
